import express from 'express'; import cors from 'cors'; import multer from 'multer'; import archiver from 'archiver'; import fs from 'node:fs'; import path from 'node:path'; import {z} from 'zod';
import {config} from './config.js'; import {emit,id,must,now,supabase} from './db.js'; import {downloadStored,inspectImage,storeMaterial} from './storage.js'; import type {ImageSettings,JobSnapshot} from './types.js';
const app=express(); app.use(cors({origin:['http://127.0.0.1:5173','http://localhost:5173']})); app.use(express.json({limit:'1mb'})); const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:20*1024*1024,files:8}});
const unwrap=(r:any):any=>{if(r.error)throw new Error(r.error.message);return r.data};
app.get('/api/health',async(_q,res,next)=>{try{const {error}=await supabase.from('projects').select('id',{head:true,count:'exact'});res.json({ok:!error,database:'supabase',storage:'supabase',model:config.model,apiKeyConfigured:Boolean(config.apiKey)});}catch(e){next(e)}});
app.get('/api/projects',async(_q,res,next)=>{try{res.json(unwrap(await supabase.from('projects').select('*').is('archived_at',null).order('updated_at',{ascending:false})));}catch(e){next(e)}});
app.post('/api/projects',async(req,res,next)=>{try{const name=z.string().trim().min(1).max(80).parse(req.body.name);const project=unwrap(await supabase.from('projects').insert({id:id(),name}).select().single());await emit('project.created',project.id,{projectId:project.id});res.status(201).json(project);}catch(e){next(e)}});
app.patch('/api/projects/:id',async(req,res,next)=>{try{const values:{name?:string;archived_at?:string|null;updated_at:string}={updated_at:now()};if(req.body.name!==undefined)values.name=z.string().trim().min(1).max(80).parse(req.body.name);if(req.body.archived!==undefined)values.archived_at=req.body.archived?now():null;const project=unwrap(await supabase.from('projects').update(values).eq('id',req.params.id).select().maybeSingle());if(!project)return res.sendStatus(404);await emit('project.updated',project.id,{projectId:project.id});res.sendStatus(204);}catch(e){next(e)}});
app.get('/api/projects/:id/workspace',async(req,res,next)=>{try{const [pr,ma,pv,cp,jo]=await Promise.all([supabase.from('projects').select('*').eq('id',req.params.id).maybeSingle(),supabase.from('materials').select('*').eq('project_id',req.params.id).order('created_at',{ascending:false}),supabase.from('prompt_versions').select('*').eq('project_id',req.params.id).order('created_at'),supabase.from('checkpoints').select('*,prompt_versions(text)').eq('project_id',req.params.id).order('created_at'),supabase.from('jobs').select('*').eq('project_id',req.params.id).order('created_at',{ascending:false}).limit(100)]);if(pr.error||!pr.data)return res.sendStatus(404);res.json({project:pr.data,materials:unwrap(ma),prompts:unwrap(pv),checkpoints:unwrap(cp).map((c:any)=>({...c,prompt_text:c.prompt_versions?.text,prompt_versions:undefined})),jobs:unwrap(jo).map((j:any)=>({...j,snapshot:j.snapshot_json,snapshot_json:undefined}))});}catch(e){next(e)}});
app.post('/api/projects/:id/materials',upload.single('image'),async(req,res,next)=>{try{if(!req.file)return res.status(400).json({error:'Choose an image.'});const meta=await inspectImage(req.file.buffer);const {data:existing}=await supabase.from('materials').select('*').eq('project_id',req.params.id).eq('sha256',meta.hash).maybeSingle();if(existing)return res.json(existing);const ext=meta.mime==='image/png'?'png':meta.mime==='image/jpeg'?'jpg':'webp';const storage_path=await storeMaterial(req.file.buffer,ext,meta.mime);const material=unwrap(await supabase.from('materials').insert({id:id(),project_id:req.params.id,label:String(req.body.label||req.file.originalname).slice(0,100),sha256:meta.hash,mime_type:meta.mime,width:meta.width,height:meta.height,size_bytes:meta.size,storage_path}).select().single());await emit('material.created',req.params.id,{materialId:material.id});res.status(201).json(material);}catch(e){next(e)}});
app.delete('/api/materials/:id',async(req,res,next)=>{try{const {data:material}=await supabase.from('materials').select('*').eq('id',req.params.id).maybeSingle();if(!material)return res.sendStatus(404);const {data:used}=await supabase.from('job_materials').select('job_id').eq('material_id',req.params.id).limit(1);if(used?.length)return res.status(409).json({error:'This material is part of immutable job history and cannot be deleted.'});unwrap(await supabase.from('materials').delete().eq('id',req.params.id).select());await supabase.storage.from('image-flow').remove([material.storage_path]);await emit('material.deleted',material.project_id,{materialId:req.params.id});res.sendStatus(204);}catch(e){next(e)}});
const jobSchema=z.object({prompt:z.string().trim().min(1).max(32000),parentCheckpointId:z.string().uuid().nullable().optional(),parentPromptVersionId:z.string().uuid().nullable().optional(),materialIds:z.array(z.string().uuid()).max(8).default([]),variations:z.number().int().min(1).max(4).default(1),idempotencyKey:z.string().min(8).max(200),settings:z.object({size:z.enum(['1024x1024','1024x1536','1536x1024']).default('1024x1024'),quality:z.enum(['low','medium','high']).default('medium'),background:z.enum(['auto','opaque','transparent']).default('auto'),outputFormat:z.enum(['png','jpeg','webp']).default('png')})});
app.post('/api/projects/:id/jobs',async(req,res,next)=>{try{const input=jobSchema.parse(req.body);const {data:existing}=await supabase.from('jobs').select('*').like('idempotency_key',`${input.idempotencyKey}:%`).order('created_at');if(existing?.length)return res.json(existing.map((j:any)=>({...j,snapshot:j.snapshot_json,snapshot_json:undefined})));if(input.parentCheckpointId){const {data}=await supabase.from('checkpoints').select('id').eq('id',input.parentCheckpointId).eq('project_id',req.params.id).maybeSingle();if(!data)return res.status(400).json({error:'Parent checkpoint does not belong to this project.'});}if(input.materialIds.length){const {data}=await supabase.from('materials').select('id').eq('project_id',req.params.id).in('id',input.materialIds);if(data?.length!==input.materialIds.length)return res.status(400).json({error:'A selected material does not belong to this project.'});}const promptId=id(),branchId=id();unwrap(await supabase.from('prompt_versions').insert({id:promptId,project_id:req.params.id,parent_prompt_version_id:input.parentPromptVersionId??null,text:input.prompt}).select());unwrap(await supabase.from('branches').insert({id:branchId,project_id:req.params.id,root_checkpoint_id:input.parentCheckpointId??null}).select());const jobs=Array.from({length:input.variations},(_,variationIndex)=>{const snapshot:JobSnapshot={prompt:input.prompt,promptVersionId:promptId,parentCheckpointId:input.parentCheckpointId??null,materialIds:input.materialIds,settings:input.settings as ImageSettings,model:config.model,variationIndex};return{id:id(),project_id:req.params.id,branch_id:branchId,status:'queued',stage:'Queued',progress:5,snapshot_json:snapshot,idempotency_key:`${input.idempotencyKey}:${variationIndex}`}});const created=unwrap(await supabase.from('jobs').insert(jobs).select());const links=created.flatMap(job=>input.materialIds.map((material_id,position)=>({job_id:job.id,material_id,position})));if(links.length)unwrap(await supabase.from('job_materials').insert(links).select());await Promise.all(created.map(job=>emit('job.queued',req.params.id,{jobId:job.id})));await supabase.from('projects').update({updated_at:now()}).eq('id',req.params.id);res.status(202).json(created.map((j:any)=>({...j,snapshot:j.snapshot_json,snapshot_json:undefined})));}catch(e){next(e)}});
app.post('/api/jobs/:id/cancel',async(req,res,next)=>{try{const {data:job}=await supabase.from('jobs').select('project_id,status').eq('id',req.params.id).maybeSingle();if(!job)return res.sendStatus(404);const values:any={cancel_requested:true,stage:'Cancelling',updated_at:now()};if(['queued','retrying'].includes(job.status)){values.status='cancelled';values.stage='Cancelled';}await supabase.from('jobs').update(values).eq('id',req.params.id).not('status','in','(completed,failed,cancelled)');await emit('job.cancelled',job.project_id,{jobId:req.params.id});res.sendStatus(204);}catch(e){next(e)}});
app.post('/api/jobs/:id/retry',async(req,res,next)=>{try{const {data:job}=await supabase.from('jobs').select('*').eq('id',req.params.id).eq('status','failed').maybeSingle();if(!job)return res.status(409).json({error:'Only failed jobs can be retried.'});unwrap(await supabase.from('jobs').update({status:'queued',stage:'Queued for manual retry',progress:5,attempt_count:0,next_attempt_at:now(),error_category:null,error_message:null,cancel_requested:false,updated_at:now()}).eq('id',req.params.id).select());await emit('job.queued',job.project_id,{jobId:req.params.id,manualRetry:true});res.sendStatus(202);}catch(e){next(e)}});
async function sendStorage(res:express.Response,storagePath:string,mime:string,name?:string){const buffer=await downloadStored(storagePath);res.type(mime);if(name)res.attachment(name);res.send(buffer)}
app.get('/api/files/:kind/:name',async(req,res,next)=>{try{const storagePath=`${req.params.kind}/${req.params.name}`;const mime=path.extname(req.params.name)==='.png'?'image/png':path.extname(req.params.name)==='.webp'?'image/webp':'image/jpeg';await sendStorage(res,storagePath,mime);}catch(e){next(e)}});
app.get('/api/checkpoints/:id/download',async(req,res,next)=>{try{const {data:cp}=await supabase.from('checkpoints').select('*').eq('id',req.params.id).maybeSingle();if(!cp)return res.sendStatus(404);await sendStorage(res,cp.storage_path,cp.mime_type,`image-flow-${cp.id}${path.extname(cp.storage_path)}`);}catch(e){next(e)}});
app.post('/api/checkpoints/download',async(req,res,next)=>{try{const ids=z.array(z.string().uuid()).min(1).max(100).parse(req.body.ids);const {data,error}=await supabase.from('checkpoints').select('*').in('id',ids);if(error)throw error;if(data.length!==ids.length)return res.status(404).json({error:'One or more checkpoints were not found.'});res.attachment('image-flow-selection.zip');const archive=archiver('zip',{zlib:{level:6}});archive.on('error',e=>res.destroy(e));archive.pipe(res);for(const [i,cp] of data.entries())archive.append(await downloadStored(cp.storage_path),{name:`${i+1}-${cp.id}${path.extname(cp.storage_path)}`});void archive.finalize();}catch(e){next(e)}});
app.get('/api/events',async(req,res)=>{const projectId=typeof req.query.projectId==='string'?req.query.projectId:null;let cursor=Number(req.header('Last-Event-ID')??req.query.after??0),busy=false;res.set({'Content-Type':'text/event-stream','Cache-Control':'no-cache',Connection:'keep-alive'});res.flushHeaders();const send=async()=>{if(busy)return;busy=true;let query=supabase.from('events').select('*').gt('id',cursor).order('id').limit(100);if(projectId)query=query.or(`project_id.eq.${projectId},project_id.is.null`);const {data}=await query;for(const event of data??[]){cursor=Number(event.id);res.write(`id: ${event.id}\nevent: ${event.type}\ndata: ${JSON.stringify(event.payload_json)}\n\n`)}busy=false};await send();const timer=setInterval(()=>{void send();res.write(': heartbeat\n\n')},1000);req.on('close',()=>clearInterval(timer))});
const webBuild=path.resolve('dist-web');if(fs.existsSync(webBuild)){app.use(express.static(webBuild));app.use((req,res,next)=>req.method==='GET'&&req.accepts('html')?res.sendFile(path.join(webBuild,'index.html')):next())}
app.use((error:unknown,_q:express.Request,res:express.Response,_n:express.NextFunction)=>{const message=error instanceof z.ZodError?error.issues[0]?.message:error instanceof Error?error.message:'Unexpected error';res.status(error instanceof z.ZodError?400:500).json({error:message})});
app.listen(config.port,config.host,()=>console.log(`Image Flow API http://${config.host}:${config.port} · Supabase`));
